sudo: required
services:
  - docker

before_install:
  - docker build -t jatinnn/docker-react -f Dockerfile.dev .

script:
  - docker run jatinnn/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'docker-react'
  env: 'docker-react-env'
  bucket_name: 'bucket name'
  bucket_path: 'bucker path'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key: $AWS_SECRET_KEY
